apiVersion: v1
kind: Pod
metadata:
  name: node-aff-required
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports: 
    - containerPort: 80
  affinity: 
     nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cpu
            operator: In
            values:
            - green 

---
apiVersion: v1
kind: Service
metadata:
  name: nodesel-svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      nodePort: 30123
