apiVersion: v1
kind: Pod
metadata:
  name: node-anti-aff-pref
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports: 
    - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
         matchExpressions:
          - key: cpu
            operator: NotIn
            values:
            - green 


---
apiVersion: v1
kind: Service
metadata:
  name: nodesel-svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      nodePort: 30123
