apiVersion: v1
kind: Pod
metadata:
  name: node-selector
  labels:
    app: myapp
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports: 
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"    

---
apiVersion: v1
kind: Service
metadata:
  name: nodesel-svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      nodePort: 30124
