apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycp
spec:
  replicas: 1
  selector:
    matchLabels:
     app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: myvol
            mountPath: /certs 
      volumes:
      - name: myvol
        secret:
          secretName: mysecret

---
apiVersion: v1
kind: Service
metadata:
  name : mydep-svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    nodePort: 30125
