apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
     app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - name: con1
          image: mysql:5.7
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mypass
                key: pass
          - name: MYSQL_DATABASE
            value: wordpress

---
apiVersion: v1
kind: Service
metadata:
  name : mydb-svc
spec:
  selector:
    app: mydb
  ports:
  - port: 3306
  
