apiVersion: v1
kind : Pod
metadata : 
   name : nodese-pod
   labels : 
      app : myapp
spec:
   containers: 
     - name : con2
       image: 966145/myserver121:latest
       ports:
        - containerPort: 80

---

apiVersion: v1
kind : Service
metadata :
   name : nodesel-svc
spec:
   type: NodePort
   selector:
     app: myapp
   ports:
     - port: 80
       nodePort: 30123
 
