apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mycm
data:
  WORDPRESS_DB_HOST: mydb-svc
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PASSWORD: test123
  WORDPRESS_DB_USER: root
  WORDPRESS_TABLE_PREFIX: wp_
